language: node_js
node_js:
- node
branches:
  only:
  - master
install: npm install
before_script:
- chmod a+x bin/*
script: gulp
after_success:
- "./bin/deploy.sh"
env:
  global:
    secure: nzftocQcmAXt+0yR+lp7S4BDzWkhrK8JE0JaTRK6no3DYAYyUur0EHB6/Gbc0WxPWr+dYAYjMCqaGqHwLduLyWnLj5mEtgyAxIPVL1oGF8nNfh6nhuNX1EpfXQpw69NZLIawfAchuYIdjynSYTIjvrsQtaOuk9EF85n5r7QNvd9YNq9+mFxvp+On3Wxfi4nvrFndxFl3jtr7yI6ComIywVgEHb761Hjs+26480gK79uh3HM+uewc6CASidJS7abVQzTl6grkxI1EbqywusmtmnmjIKsBbpE4RBa6WL6Hkvlheyv6/UAq1wakZ7kderiDLMz8LyXBZo4jM+Tj+W6se61N9bjrtXS7xOf3gAZEAYHE+kWT7w6yG4qT4OGAS353jiuypaw6D5Vk6gftGQ9tOLkOU/M5oOu9C2YqrPWhqGNhpK1DFwP56i3nUG4BGVx9wfuiim0/sNS8BFR/JVV2m2pTzMXacZmmSHpZDNAi8oRlkbmwnt06ZWj8T5HcTavlX69hDf6mYR+LI9GMKAGho39S7tBFHkVnfVU+8lINtih441FNbc/PzwRibzBchgMLxR3rvWdRjYdX5j81FTpL+kO9VTj7xYb+yFzKc9GjGi1NblNaklezK714YPrZYvkAEVYCc9R9vicgoFXgzByiwiwecjL8SYgqQmtOidJ0O2s=
